@startuml Sequence Diagram (SD) - Create sale announcement
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
participant ":CreateSaleAnnouncementController" as CTRL
participant "propertyType\n:PropertyType" as PTR

autonumber 38
-> CTRL : getPropertyTypes()
activate CTRL
	CTRL -> PTR : getPropertyTypes()
	activate PTR
		PTR -> CTRL : propertyTypeList
	deactivate PTR
deactivate CTRL
@enduml