@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram Parcial Get Acess to Repositorys List (SSD)

autonumber

'hide footbox
participant ":ScheduleVisitController" as CTRL

participant ":Repositories" as RepositorySingleton

autonumber 3

        activate CTRL

        CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

            RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

        deactivate CTRL

@enduml