@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Sequence Diagram Full (SD)
autonumber

'Client Schedule Visit

'hide footbox
actor "Client" as User
participant ":ScheduleVisitUI" as UI
participant ":ScheduleVisitController" as CTRL

activate User

    User -> UI : asks to Schedule a Visit property
        activate UI

        UI -> CTRL** : create
            activate CTRL
        ref over CTRL
            Get Repositories
        end ref
            deactivate CTRL

        UI -> CTRL :listAndChoosePropertyType()
                activate CTRL
        ref over CTRL
            Get PropertyTypeList
        end ref
        CTRL --> UI : propertyTypesList
                deactivate CTRL

        UI --> User : shows Property Type List \n and asks to select one
        deactivate UI

    User -> UI : selects a Property Type
            activate UI

        UI  ->  UI: keepPropertyType

        UI -> CTRL :listAndChooseBusinessType()
                activate CTRL
        ref over CTRL
            Get BusinessTypeList
        end ref
        CTRL --> UI : businessTypesList
                deactivate CTRL

        UI --> User : shows Business Type List \n and asks to select one
        deactivate UI

    User -> UI : selects a Business Type
            activate UI

        UI  ->  UI: keepBusinessType

        UI-> CTRL: listAndDisplayandChooseAdvertisementDTO\n(propertyTypeChoice, businessTypeChoice)
            activate CTRL

        ref over CTRL
            Get AdvertismentDTOListSortedByDate
        end ref

            CTRL -> UI : AdvertisementDTOListSortedByDate
            deactivate CTRL

        UI --> User : shows AdvertismentDTO List \n and asks to select one
        deactivate UI

    User -> UI : selects a AdvertismentDTO
            activate UI

        UI  ->  UI: keepAdvertismentDTO

        UI -> User : ask data (date)
        deactivate UI

    User -> UI : types asked data (date)
        activate UI

        UI  ->  UI: keep data (date)

        UI -> User : ask data (hour)
        deactivate UI

    User -> UI : types asked data (hour)
            activate UI

        UI  ->  UI: keep data (hour)

        UI -> CTRL: getClientEmail()
            activate CTRL

        ref over CTRL
            Get GetClientEmail
        end ref

            CTRL -> UI: clientEmail
            deactivate CTRL

        UI -> UI: keepClientEmail


        UI -> CTRL: getVerifyVisitTimeFree(adchoiceVisit,date,hour)
            activate CTRL

        ref over CTRL
            Verify time choice free
        end ref

            CTRL  -> UI: getVerifyVisitTimeFree(adchoiceVisit,date,hour)=true
            deactivate CTRL

        UI -> User: Display Visit conditions\n and ask for validation (YES/NO)
        deactivate UI

    User -> UI: input: validation (YES/NO)
        activate UI



alt validation = YES

        UI -> User : displays operation success
        deactivate UI
end

deactivate User






@enduml