@startuml Sequence Diagram - List Property Request
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Sequence Diagram Full - List Property Request
autonumber

'hide footbox
participant ":ListPropertyRequestsController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "requestRepository\n:RequestRepository" as RequestRepository

autonumber 6

activate CTRL

	opt doesn't have agent info yet
		CTRL -> CTRL : getAgentFromSession()

			ref over CTRL
				Get Agent Info
			end ref

autonumber 17
		CTRL --> CTRL : employee
	end
	CTRL -> PLAT : getRequestRepository()
	activate PLAT
		PLAT --> CTRL : RequestRepository
	deactivate PLAT
	CTRL -> RequestRepository : getRequestsByAgent(agent)
	activate RequestRepository
		RequestRepository --> CTRL : requestsList
	deactivate RequestRepository
deactivate CTRL

@enduml