@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Unregistered User" as ADM
participant ":RegisterUserUI" as UI
participant ":RegisterUserController" as CTRL
participant ":Repositories" as ORG
participant "repositories\n:Repositories" as REPO
participant "authenticationRepository\n:AuthenticationRepository" as AuthenticationRepository
participant "personRepository\n:PersonRepository" as PersonRepository






activate ADM

    ADM -> UI : asks to register in the application


    activate UI

        UI -> CTRL**: create()


        CTRL -> ORG : getInstance()
        activate CTRL
        activate ORG

          ORG --> CTRL: repositories
        deactivate ORG

        UI -->ADM: asks for name

        ADM -> UI: sends data

        UI -> UI:keepName

        UI -->ADM: asks for e-mail

                ADM -> UI: sends data

        UI -> UI:keepEmail

        UI -->ADM: asks for password

                ADM -> UI: sends data

        UI -> UI:keepPassword

        UI -->ADM: asks for citizenNumber

                        ADM -> UI: sends data

                UI -> UI:keepCitizenNumber


        UI -->ADM: asks for tin

                        ADM -> UI: sends data

                UI -> UI:keepTin

        UI -->ADM: asks for phone number

                 ADM -> UI: sends data

        UI -> UI:keepPhoneNumber

        UI -> ADM: asks if the unregistered user wants to give the new user location
                                    ADM -> UI:true/false
                                    UI-> UI :option

                                    group opt [true]


        UI -->ADM: asks for street

                         ADM -> UI: sends data

                UI -> UI: keepStreet



       UI -->ADM: asks for zipcode

                                ADM -> UI: sends data

                       UI -> UI: keepZipCode


       UI -->ADM: asks for state

                                ADM -> UI: sends data

                       UI -> UI: keepStateUS

        UI -->ADM: asks for city

                                 ADM -> UI: sends data

                        UI -> UI: keepCity

       UI -->ADM: asks for district

                                ADM -> UI: sends data

                       UI -> UI: keepDistrict



         end group




        UI -> CTRL : registerUserWithClientAndOwnerPerms(keepName,keepEmail,keepPassword,Roles,keepCitizenNumber,keepPhoneNumber,keepTin,keepStreet,keepZipCode,keepStateUS,keepCity,keepDistrict,option)

        CTRL -> REPO: getAuthenticationRepository()

        activate REPO

        REPO --> CTRL: authenticationRepository

        deactivate REPO

        CTRL -> AuthenticationRepository : addUserWithRoles(keepName, keepEmail, keepPassword, Roles)

            activate AuthenticationRepository

        AuthenticationRepository --> CTRL: true/false





        deactivate AuthenticationRepository


        group opt [true]

            CTRL -> REPO: getPersonRepository()

            REPO --> CTRL : personRepository

            group alt  [option=true]

            CTRL -> PersonRepository: addPerson(keepName,keepEmail,keepCitizenNumber,keepTin,keepPhoneNumber,keepStreet,keepZipCode,keepStateUS,keepCity,keepDistrict)

            activate PersonRepository

            PersonRepository --> CTRL:person

            deactivate PersonRepository

            else option=false

            CTRL -> PersonRepository: addPerson(keepName,keepEmail,keepCitizenNumber,keepTin,keepPhoneNumber)

                        activate PersonRepository

                        PersonRepository --> CTRL:person

                        deactivate PersonRepository

        end group

        end group
        CTRL --> UI:true/false
        deactivate CTRL

        UI --> ADM: display operation success

      deactivate UI

deactivate ADM

@enduml