@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram Parcial Get Business Type List (SSD)

'hide footbox

participant ":SubmiPropertyController" as CTRL

participant "repositories\n:Repositories" as repositories
participant "businessTypeRepository\n:BusinessTypeRepository" as BusinessTypeRepository

autonumber 76

            CTRL -> repositories : getBusinessTypeRepository()
            activate repositories

                repositories --> CTRL: BusinessTypeRepository
                deactivate repositories

            CTRL -> BusinessTypeRepository: getBusinessTypeList()
            activate BusinessTypeRepository

                BusinessTypeRepository -> CTRL: businessTypeList
                deactivate BusinessTypeRepository



@enduml