@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram Parcial Get Acess to Repositorys List (SSD)

autonumber

'hide footbox
participant ":RespondBookingRequestController" as CTRL

participant "userSession\n:UserSession" as userSession

autonumber 5

        activate CTRL

            CTRL -> userSession : getAgentEmail()
            activate userSession

                userSession -> CTRL: agentEmail
                deactivate userSession

        deactivate CTRL


@enduml