@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram Parcial Get Acess to Repositorys List (SSD)

autonumber

'hide footbox
participant ":RespondBookingRequestController" as CTRL

participant "advertisementRepository\n:AdvertisementRepository" as advertisementRepository

autonumber 48

    activate CTRL

            CTRL -> advertisementRepository: getClientEmailFromVisit(keepVisitRequest)
            activate advertisementRepository

            advertisementRepository -> CTRL: keepClientEmail
            deactivate advertisementRepository

    deactivate CTRL

@enduml