@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram Parcial Get Business Type List (SSD)

'hide footbox

participant ":MakeOfferController" as CTRL

participant "businessTypeEnum\n:BusinessTypeEnum" as BusinessTypeEnum

autonumber 15

        activate CTRL

            CTRL -> BusinessTypeEnum: getBusinessTypeList()
            activate BusinessTypeEnum

                BusinessTypeEnum -> CTRL: businessTypeList
                deactivate BusinessTypeEnum

        deactivate CTRL


@enduml