@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram Parcial Get Business Type List (SSD)

'hide footbox

participant ":ScheduleVisitController" as CTRL

participant "businessTypeEnum\n:BusinessTypeEnum" as businessTypeEnum

autonumber 15

        activate CTRL

            CTRL -> businessTypeEnum: getBusinessTypeList()
            activate businessTypeEnum

                businessTypeEnum -> CTRL: businessTypeList
                deactivate businessTypeEnum

        deactivate CTRL

@enduml