@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram Parcial Get Property Type List (SSD)


participant ":ScheduleVisitController" as CTRL

participant "propertyTypeEnum\n:PropertyTypeEnum" as propertyTypeEnum


autonumber 6

        activate CTRL

            CTRL -> propertyTypeEnum : getPropertyTypesList()
                activate propertyTypeEnum

                propertyTypeEnum --> CTRL : PropertyTypesList
                deactivate propertyTypeEnum

        deactivate CTRL

@enduml